//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EULAForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EULAForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.EULAForm", typeof(EULAForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Text zum Kopieren! ähnelt.
        /// </summary>
        internal static string de_CopiedFail {
            get {
                return ResourceManager.GetString("de_CopiedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In die Zwischenablage kopiert! ähnelt.
        /// </summary>
        internal static string de_CopiedSuccess {
            get {
                return ResourceManager.GetString("de_CopiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Übersicht
        ///Diese Endbenutzer-Lizenzvereinbarung (EULA) ist ein rechtlicher Vertrag zwischen Ihnen, dem Endbenutzer, und xscr33m, dem Entwickler von xscr33mLabs Tools, einer Desktop-Anwendung, die in C# geschrieben wurde. Durch die Installation oder Verwendung von xscr33mLabs Tools erklären Sie sich mit den Bedingungen dieser EULA einverstanden.
        ///
        ///2. Lizenz
        ///Die Entwickler von xscr33mLabs Tools gewähren Ihnen hiermit eine nicht-exklusive und nicht übertragbare Lizenz zur Installation und Verwendung von x [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string de_EULAText {
            get {
                return ResourceManager.GetString("de_EULAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ist die Endbenutzer-Lizenzvereinbarung (EULA) für xscr33mLabs Tools ähnelt.
        /// </summary>
        internal static string de_ReviewTitle {
            get {
                return ResourceManager.GetString("de_ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um TraderPlusEditor zu verwenden, akzeptiere bitte das Endbenutzerlizenzabkommen. ähnelt.
        /// </summary>
        internal static string de_Title {
            get {
                return ResourceManager.GetString("de_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No text to copy! ähnelt.
        /// </summary>
        internal static string en_CopiedFail {
            get {
                return ResourceManager.GetString("en_CopiedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to Clipboard! ähnelt.
        /// </summary>
        internal static string en_CopiedSuccess {
            get {
                return ResourceManager.GetString("en_CopiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. overview
        ///This End User License Agreement (EULA) is a legal agreement between you, the end user, and xscr33m, the developer of xscr33mLabs Tools, a desktop application written in C#. By installing or using xscr33mLabs Tools, you agree to be bound by the terms of this EULA.
        ///
        ///2. license
        ///The developers of xscr33mLabs Tools hereby grant you a non-exclusive and non-transferable license to install and use xscr33mLabs Tools on a single computer or device that you own or control. This EULA does not permit you [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string en_EULAText {
            get {
                return ResourceManager.GetString("en_EULAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is the End User License Agreement (EULA) for xscr33mLabs Tools ähnelt.
        /// </summary>
        internal static string en_ReviewTitle {
            get {
                return ResourceManager.GetString("en_ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To use TraderPlusEditor, please accept the End User License Agreement. ähnelt.
        /// </summary>
        internal static string en_Title {
            get {
                return ResourceManager.GetString("en_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pas de texte à copier ! ähnelt.
        /// </summary>
        internal static string fr_CopiedFail {
            get {
                return ResourceManager.GetString("fr_CopiedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copié dans le presse-papiers ! ähnelt.
        /// </summary>
        internal static string fr_CopiedSuccess {
            get {
                return ResourceManager.GetString("fr_CopiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. aperçu
        ///Ce Contrat de Licence Utilisateur Final (CLUF) est un contrat légal entre vous, l&apos;utilisateur final, et xscr33m, le développeur de xscr33mLabs Tools, une application de bureau écrite en C#. En installant ou en utilisant xscr33mLabs Tools, vous acceptez d&apos;être lié par les termes de ce CLUF.
        ///
        ///2. ème licence
        ///Les développeurs de xscr33mLabs Tools vous accordent par la présente une licence non exclusive et non transférable pour l&apos;installation et l&apos;utilisation de xscr33mLabs Tools sur un seul ordina [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string fr_EULAText {
            get {
                return ResourceManager.GetString("fr_EULAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ceci est le Contrat de Licence Utilisateur Final (CLUF) pour les outils xscr33mLabs Tools ähnelt.
        /// </summary>
        internal static string fr_ReviewTitle {
            get {
                return ResourceManager.GetString("fr_ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pour pouvoir utiliser TraderPlusEditor, veuillez accepter le Contrat de Licence Utilisateur Final. ähnelt.
        /// </summary>
        internal static string fr_Title {
            get {
                return ResourceManager.GetString("fr_Title", resourceCulture);
            }
        }
    }
}
