//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.InfoForm", typeof(InfoForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trete dem Discord bei ähnelt.
        /// </summary>
        internal static string de_ButtonDiscord {
            get {
                return ResourceManager.GetString("de_ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehr xscr33mLabs Tools ähnelt.
        /// </summary>
        internal static string de_ButtonGithub {
            get {
                return ResourceManager.GetString("de_ButtonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spendiere mir einen Kaffee ähnelt.
        /// </summary>
        internal static string de_ButtonPayPal {
            get {
                return ResourceManager.GetString("de_ButtonPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xscr33m&apos;s DayZ Mods ähnelt.
        /// </summary>
        internal static string de_ButtonSteam {
            get {
                return ResourceManager.GetString("de_ButtonSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join the Discord ähnelt.
        /// </summary>
        internal static string en_ButtonDiscord {
            get {
                return ResourceManager.GetString("en_ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More xscr33mLabs Tools ähnelt.
        /// </summary>
        internal static string en_ButtonGithub {
            get {
                return ResourceManager.GetString("en_ButtonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy me a coffee ähnelt.
        /// </summary>
        internal static string en_ButtonPayPal {
            get {
                return ResourceManager.GetString("en_ButtonPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xscr33m&apos;s DayZ Mods ähnelt.
        /// </summary>
        internal static string en_ButtonSteam {
            get {
                return ResourceManager.GetString("en_ButtonSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rejoindre le Discord ähnelt.
        /// </summary>
        internal static string fr_ButtonDiscord {
            get {
                return ResourceManager.GetString("fr_ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plus d&apos;outils xscr33mLabs ähnelt.
        /// </summary>
        internal static string fr_ButtonGithub {
            get {
                return ResourceManager.GetString("fr_ButtonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offre-moi un café ähnelt.
        /// </summary>
        internal static string fr_ButtonPayPal {
            get {
                return ResourceManager.GetString("fr_ButtonPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mods DayZ de xscr33m ähnelt.
        /// </summary>
        internal static string fr_ButtonSteam {
            get {
                return ResourceManager.GetString("fr_ButtonSteam", resourceCulture);
            }
        }
    }
}
