//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSONValidatorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSONValidatorRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.JSONValidatorRes", typeof(JSONValidatorRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Verschönern von JSON:  ähnelt.
        /// </summary>
        internal static string de_BeautifyError1 {
            get {
                return ResourceManager.GetString("de_BeautifyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige JSON-Datei. ähnelt.
        /// </summary>
        internal static string de_ExeptionJSON {
            get {
                return ResourceManager.GetString("de_ExeptionJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht unterstütztes Dateiformat. ähnelt.
        /// </summary>
        internal static string de_ExeptionNoSup {
            get {
                return ResourceManager.GetString("de_ExeptionNoSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei war nicht gültig! ähnelt.
        /// </summary>
        internal static string de_Invalid {
            get {
                return ResourceManager.GetString("de_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Lesen der Datei:  ähnelt.
        /// </summary>
        internal static string de_ReadError {
            get {
                return ResourceManager.GetString("de_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei erfolgreich validiert und verschönert! ähnelt.
        /// </summary>
        internal static string de_Success {
            get {
                return ResourceManager.GetString("de_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JSON-Validierungsfehler:  ähnelt.
        /// </summary>
        internal static string de_ValidJsonError {
            get {
                return ResourceManager.GetString("de_ValidJsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error beautifying JSON:  ähnelt.
        /// </summary>
        internal static string en_BeautifyError1 {
            get {
                return ResourceManager.GetString("en_BeautifyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid JSON file. ähnelt.
        /// </summary>
        internal static string en_ExeptionJSON {
            get {
                return ResourceManager.GetString("en_ExeptionJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported file format. ähnelt.
        /// </summary>
        internal static string en_ExeptionNoSup {
            get {
                return ResourceManager.GetString("en_ExeptionNoSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File was not valid! ähnelt.
        /// </summary>
        internal static string en_Invalid {
            get {
                return ResourceManager.GetString("en_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error reading file:  ähnelt.
        /// </summary>
        internal static string en_ReadError {
            get {
                return ResourceManager.GetString("en_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File successfully validated and beautified! ähnelt.
        /// </summary>
        internal static string en_Success {
            get {
                return ResourceManager.GetString("en_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JSON validation error:  ähnelt.
        /// </summary>
        internal static string en_ValidJsonError {
            get {
                return ResourceManager.GetString("en_ValidJsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur d&apos;embellissement du JSON :  ähnelt.
        /// </summary>
        internal static string fr_BeautifyError1 {
            get {
                return ResourceManager.GetString("fr_BeautifyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fichier JSON non valide. ähnelt.
        /// </summary>
        internal static string fr_ExeptionJSON {
            get {
                return ResourceManager.GetString("fr_ExeptionJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format de fichier non pris en charge. ähnelt.
        /// </summary>
        internal static string fr_ExeptionNoSup {
            get {
                return ResourceManager.GetString("fr_ExeptionNoSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le fichier n&apos;est pas valide ! ähnelt.
        /// </summary>
        internal static string fr_Invalid {
            get {
                return ResourceManager.GetString("fr_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur de lecture du fichier :  ähnelt.
        /// </summary>
        internal static string fr_ReadError {
            get {
                return ResourceManager.GetString("fr_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fichier validé et embelli avec succès ! ähnelt.
        /// </summary>
        internal static string fr_Success {
            get {
                return ResourceManager.GetString("fr_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur de validation JSON :  ähnelt.
        /// </summary>
        internal static string fr_ValidJsonError {
            get {
                return ResourceManager.GetString("fr_ValidJsonError", resourceCulture);
            }
        }
    }
}
