//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autom. Berechnung ähnelt.
        /// </summary>
        internal static string de_CheckBoxAutoCalculation {
            get {
                return ResourceManager.GetString("de_CheckBoxAutoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Destock bei Neustart ähnelt.
        /// </summary>
        internal static string de_CheckBoxAutoDestock {
            get {
                return ResourceManager.GetString("de_CheckBoxAutoDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard-Händlerbestand ähnelt.
        /// </summary>
        internal static string de_CheckBoxDefaultTraderStock {
            get {
                return ResourceManager.GetString("de_CheckBoxDefaultTraderStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaufpreis ähnelt.
        /// </summary>
        internal static string de_GridViewBuyPrice {
            get {
                return ResourceManager.GetString("de_GridViewBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie ähnelt.
        /// </summary>
        internal static string de_GridViewCategorie {
            get {
                return ResourceManager.GetString("de_GridViewCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Koeffizient ähnelt.
        /// </summary>
        internal static string de_GridViewCoefficient {
            get {
                return ResourceManager.GetString("de_GridViewCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destock Koeffizient ähnelt.
        /// </summary>
        internal static string de_GridViewDestock {
            get {
                return ResourceManager.GetString("de_GridViewDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Bestand ähnelt.
        /// </summary>
        internal static string de_GridViewMaxStock {
            get {
                return ResourceManager.GetString("de_GridViewMaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produktname ähnelt.
        /// </summary>
        internal static string de_GridViewProduct {
            get {
                return ResourceManager.GetString("de_GridViewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verkaufpreis ähnelt.
        /// </summary>
        internal static string de_GridViewSellPrice {
            get {
                return ResourceManager.GetString("de_GridViewSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handelsmenge ähnelt.
        /// </summary>
        internal static string de_GridViewTradeQty {
            get {
                return ResourceManager.GetString("de_GridViewTradeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaufpreis ähnelt.
        /// </summary>
        internal static string de_LabelBuyPrice {
            get {
                return ResourceManager.GetString("de_LabelBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorien ähnelt.
        /// </summary>
        internal static string de_LabelCategories {
            get {
                return ResourceManager.GetString("de_LabelCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Koeffizient ähnelt.
        /// </summary>
        internal static string de_LabelCoefficent {
            get {
                return ResourceManager.GetString("de_LabelCoefficent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destock Koeffizient ähnelt.
        /// </summary>
        internal static string de_LabelDestockCoefficient {
            get {
                return ResourceManager.GetString("de_LabelDestockCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Bestand ähnelt.
        /// </summary>
        internal static string de_LabelMaxStock {
            get {
                return ResourceManager.GetString("de_LabelMaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Kategoriename ähnelt.
        /// </summary>
        internal static string de_LabelNewCategorie {
            get {
                return ResourceManager.GetString("de_LabelNewCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Produktname ähnelt.
        /// </summary>
        internal static string de_LabelNewProductName {
            get {
                return ResourceManager.GetString("de_LabelNewProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verkaufpreis ähnelt.
        /// </summary>
        internal static string de_LabelSellPrice {
            get {
                return ResourceManager.GetString("de_LabelSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handelsmenge ähnelt.
        /// </summary>
        internal static string de_LabelTradeQuantity {
            get {
                return ResourceManager.GetString("de_LabelTradeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string de_LabelVersion {
            get {
                return ResourceManager.GetString("de_LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Calculation ähnelt.
        /// </summary>
        internal static string en_CheckBoxAutoCalculation {
            get {
                return ResourceManager.GetString("en_CheckBoxAutoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Destock at Restart ähnelt.
        /// </summary>
        internal static string en_CheckBoxAutoDestock {
            get {
                return ResourceManager.GetString("en_CheckBoxAutoDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Trader Stock ähnelt.
        /// </summary>
        internal static string en_CheckBoxDefaultTraderStock {
            get {
                return ResourceManager.GetString("en_CheckBoxDefaultTraderStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy Price ähnelt.
        /// </summary>
        internal static string en_GridViewBuyPrice {
            get {
                return ResourceManager.GetString("en_GridViewBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        internal static string en_GridViewCategorie {
            get {
                return ResourceManager.GetString("en_GridViewCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coefficient ähnelt.
        /// </summary>
        internal static string en_GridViewCoefficient {
            get {
                return ResourceManager.GetString("en_GridViewCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destock Coeffient ähnelt.
        /// </summary>
        internal static string en_GridViewDestock {
            get {
                return ResourceManager.GetString("en_GridViewDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Stock ähnelt.
        /// </summary>
        internal static string en_GridViewMaxStock {
            get {
                return ResourceManager.GetString("en_GridViewMaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product Name ähnelt.
        /// </summary>
        internal static string en_GridViewProduct {
            get {
                return ResourceManager.GetString("en_GridViewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sell Price ähnelt.
        /// </summary>
        internal static string en_GridViewSellPrice {
            get {
                return ResourceManager.GetString("en_GridViewSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Quantity ähnelt.
        /// </summary>
        internal static string en_GridViewTradeQty {
            get {
                return ResourceManager.GetString("en_GridViewTradeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy Price ähnelt.
        /// </summary>
        internal static string en_LabelBuyPrice {
            get {
                return ResourceManager.GetString("en_LabelBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        internal static string en_LabelCategories {
            get {
                return ResourceManager.GetString("en_LabelCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coefficent ähnelt.
        /// </summary>
        internal static string en_LabelCoefficent {
            get {
                return ResourceManager.GetString("en_LabelCoefficent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destock Coefficent ähnelt.
        /// </summary>
        internal static string en_LabelDestockCoefficient {
            get {
                return ResourceManager.GetString("en_LabelDestockCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Stock ähnelt.
        /// </summary>
        internal static string en_LabelMaxStock {
            get {
                return ResourceManager.GetString("en_LabelMaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Categorie Name ähnelt.
        /// </summary>
        internal static string en_LabelNewCategorie {
            get {
                return ResourceManager.GetString("en_LabelNewCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Product Name ähnelt.
        /// </summary>
        internal static string en_LabelNewProductName {
            get {
                return ResourceManager.GetString("en_LabelNewProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sell Price ähnelt.
        /// </summary>
        internal static string en_LabelSellPrice {
            get {
                return ResourceManager.GetString("en_LabelSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Quantity ähnelt.
        /// </summary>
        internal static string en_LabelTradeQuantity {
            get {
                return ResourceManager.GetString("en_LabelTradeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string en_LabelVersion {
            get {
                return ResourceManager.GetString("en_LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calcul automatique ähnelt.
        /// </summary>
        internal static string fr_CheckBoxAutoCalculation {
            get {
                return ResourceManager.GetString("fr_CheckBoxAutoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destockage automatique au redémarrage ähnelt.
        /// </summary>
        internal static string fr_CheckBoxAutoDestock {
            get {
                return ResourceManager.GetString("fr_CheckBoxAutoDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stock par défaut du trader ähnelt.
        /// </summary>
        internal static string fr_CheckBoxDefaultTraderStock {
            get {
                return ResourceManager.GetString("fr_CheckBoxDefaultTraderStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acheter le prix ähnelt.
        /// </summary>
        internal static string fr_GridViewBuyPrice {
            get {
                return ResourceManager.GetString("fr_GridViewBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catégorie ähnelt.
        /// </summary>
        internal static string fr_GridViewCategorie {
            get {
                return ResourceManager.GetString("fr_GridViewCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coefficient ähnelt.
        /// </summary>
        internal static string fr_GridViewCoefficient {
            get {
                return ResourceManager.GetString("fr_GridViewCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coefficient de déstockage ähnelt.
        /// </summary>
        internal static string fr_GridViewDestock {
            get {
                return ResourceManager.GetString("fr_GridViewDestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stock maximum ähnelt.
        /// </summary>
        internal static string fr_GridViewMaxStock {
            get {
                return ResourceManager.GetString("fr_GridViewMaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nom du produit ähnelt.
        /// </summary>
        internal static string fr_GridViewProduct {
            get {
                return ResourceManager.GetString("fr_GridViewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prix de vente ähnelt.
        /// </summary>
        internal static string fr_GridViewSellPrice {
            get {
                return ResourceManager.GetString("fr_GridViewSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantité commerciale ähnelt.
        /// </summary>
        internal static string fr_GridViewTradeQty {
            get {
                return ResourceManager.GetString("fr_GridViewTradeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acheter le prix ähnelt.
        /// </summary>
        internal static string fr_LabelBuyPrice {
            get {
                return ResourceManager.GetString("fr_LabelBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catégories ähnelt.
        /// </summary>
        internal static string fr_LabelCategories {
            get {
                return ResourceManager.GetString("fr_LabelCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coefficent ähnelt.
        /// </summary>
        internal static string fr_LabelCoefficent {
            get {
                return ResourceManager.GetString("fr_LabelCoefficent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destockage Coefficent ähnelt.
        /// </summary>
        internal static string fr_LabelDestockCoefficient {
            get {
                return ResourceManager.GetString("fr_LabelDestockCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stock maximum ähnelt.
        /// </summary>
        internal static string fr_LabelMaxStock {
            get {
                return ResourceManager.GetString("fr_LabelMaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nouveau nom de catégorie ähnelt.
        /// </summary>
        internal static string fr_LabelNewCategorie {
            get {
                return ResourceManager.GetString("fr_LabelNewCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nouveau nom de produit ähnelt.
        /// </summary>
        internal static string fr_LabelNewProductName {
            get {
                return ResourceManager.GetString("fr_LabelNewProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prix de vente ähnelt.
        /// </summary>
        internal static string fr_LabelSellPrice {
            get {
                return ResourceManager.GetString("fr_LabelSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantité commerciale ähnelt.
        /// </summary>
        internal static string fr_LabelTradeQuantity {
            get {
                return ResourceManager.GetString("fr_LabelTradeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string fr_LabelVersion {
            get {
                return ResourceManager.GetString("fr_LabelVersion", resourceCulture);
            }
        }
    }
}
