//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.MessageForm", typeof(MessageForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string de_ButtonNo {
            get {
                return ResourceManager.GetString("de_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        internal static string de_ButtonOk {
            get {
                return ResourceManager.GetString("de_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string de_ButtonYes {
            get {
                return ResourceManager.GetString("de_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; und alle enthaltenen Produkte werden unwiderruflich gelöscht! 
        ///
        ///Bist du sicher, dass du fortfahren möchtest? ähnelt.
        /// </summary>
        internal static string de_CategoryDelete {
            get {
                return ResourceManager.GetString("de_CategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du die Datei wirklich schließen? ähnelt.
        /// </summary>
        internal static string de_CloseFile {
            get {
                return ResourceManager.GetString("de_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungespeicherte Änderungen festgestellt! 
        ///
        ///Willst du wirklich die Änderungen verwerfen und die Datei schließen? ähnelt.
        /// </summary>
        internal static string de_DiscardChanges {
            get {
                return ResourceManager.GetString("de_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die folgenden Einträge haben ungültige Werte:
        ///
        /// ähnelt.
        /// </summary>
        internal static string de_InvalidEntries {
            get {
                return ResourceManager.GetString("de_InvalidEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das/die folgende(n) Produkt(e) wird/werden gelöscht:
        ///
        /// ähnelt.
        /// </summary>
        internal static string de_ProductDelete {
            get {
                return ResourceManager.GetString("de_ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und  ähnelt.
        /// </summary>
        internal static string de_ProductDelete2 {
            get {
                return ResourceManager.GetString("de_ProductDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  weitere...
        ///
        /// ähnelt.
        /// </summary>
        internal static string de_ProductDelete3 {
            get {
                return ResourceManager.GetString("de_ProductDelete3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Bist du sicher, dass du fortfahren möchtest? ähnelt.
        /// </summary>
        internal static string de_ProductDelete4 {
            get {
                return ResourceManager.GetString("de_ProductDelete4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine neue TraderPlusPriceConfig.json wird im Export-Ordner erstellt. 
        ///
        ///Bist du sicher, dass du fortfahren möchtest? ähnelt.
        /// </summary>
        internal static string de_SaveConfirm {
            get {
                return ResourceManager.GetString("de_SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Produkte der markierten Kategorie erhalten diesen Wert! 
        ///
        ///Bist du sicher, dass du fortfahren möchtest?  ähnelt.
        /// </summary>
        internal static string de_SetAllWarning {
            get {
                return ResourceManager.GetString("de_SetAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler! ähnelt.
        /// </summary>
        internal static string de_TitleError {
            get {
                return ResourceManager.GetString("de_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string de_TitleInfo {
            get {
                return ResourceManager.GetString("de_TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frage ähnelt.
        /// </summary>
        internal static string de_TitleQuestion {
            get {
                return ResourceManager.GetString("de_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung! ähnelt.
        /// </summary>
        internal static string de_TitleWarning {
            get {
                return ResourceManager.GetString("de_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string en_ButtonNo {
            get {
                return ResourceManager.GetString("en_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        internal static string en_ButtonOk {
            get {
                return ResourceManager.GetString("en_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string en_ButtonYes {
            get {
                return ResourceManager.GetString("en_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; and all its containing products will be deleted permanently!
        ///
        ///Are you sure you want to continue? ähnelt.
        /// </summary>
        internal static string en_CategoryDelete {
            get {
                return ResourceManager.GetString("en_CategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to close the file? ähnelt.
        /// </summary>
        internal static string en_CloseFile {
            get {
                return ResourceManager.GetString("en_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved changes detected! 
        ///
        ///Do you really want to discard changes and close the file? ähnelt.
        /// </summary>
        internal static string en_DiscardChanges {
            get {
                return ResourceManager.GetString("en_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following entries have invalid values:
        ///
        /// ähnelt.
        /// </summary>
        internal static string en_InvalidEntries {
            get {
                return ResourceManager.GetString("en_InvalidEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following product(s) will be deleted: 
        ///
        /// ähnelt.
        /// </summary>
        internal static string en_ProductDelete {
            get {
                return ResourceManager.GetString("en_ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and  ähnelt.
        /// </summary>
        internal static string en_ProductDelete2 {
            get {
                return ResourceManager.GetString("en_ProductDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  more...
        ///
        /// ähnelt.
        /// </summary>
        internal static string en_ProductDelete3 {
            get {
                return ResourceManager.GetString("en_ProductDelete3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Are you sure you want to continue? ähnelt.
        /// </summary>
        internal static string en_ProductDelete4 {
            get {
                return ResourceManager.GetString("en_ProductDelete4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new TraderPlusPriceConfig.json will be created in the export folder. 
        ///
        ///Are you sure you want to continue? ähnelt.
        /// </summary>
        internal static string en_SaveConfirm {
            get {
                return ResourceManager.GetString("en_SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All products of marked category will get this value! 
        ///
        ///Are you sure you want to continue? ähnelt.
        /// </summary>
        internal static string en_SetAllWarning {
            get {
                return ResourceManager.GetString("en_SetAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string en_TitleError {
            get {
                return ResourceManager.GetString("en_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string en_TitleInfo {
            get {
                return ResourceManager.GetString("en_TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string en_TitleQuestion {
            get {
                return ResourceManager.GetString("en_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning! ähnelt.
        /// </summary>
        internal static string en_TitleWarning {
            get {
                return ResourceManager.GetString("en_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non ähnelt.
        /// </summary>
        internal static string fr_ButtonNo {
            get {
                return ResourceManager.GetString("fr_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string fr_ButtonOk {
            get {
                return ResourceManager.GetString("fr_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oui ähnelt.
        /// </summary>
        internal static string fr_ButtonYes {
            get {
                return ResourceManager.GetString("fr_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die et tous les produits qu&apos;il contient seront définitivement supprimés !
        ///
        ///Êtes-vous sûr de vouloir continuer ? ähnelt.
        /// </summary>
        internal static string fr_CategoryDelete {
            get {
                return ResourceManager.GetString("fr_CategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voulez-vous vraiment fermer le dossier ? ähnelt.
        /// </summary>
        internal static string fr_CloseFile {
            get {
                return ResourceManager.GetString("fr_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modifications non enregistrées détectées ! 
        ///
        ///Voulez-vous vraiment annuler les modifications et fermer le fichier ? ähnelt.
        /// </summary>
        internal static string fr_DiscardChanges {
            get {
                return ResourceManager.GetString("fr_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Les entrées suivantes ont des valeurs non valides :
        ///
        /// ähnelt.
        /// </summary>
        internal static string fr_InvalidEntries {
            get {
                return ResourceManager.GetString("fr_InvalidEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le(s) produit(s) suivant(s) sera(ont) supprimé(s) :
        ///
        /// ähnelt.
        /// </summary>
        internal static string fr_ProductDelete {
            get {
                return ResourceManager.GetString("fr_ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die et  ähnelt.
        /// </summary>
        internal static string fr_ProductDelete2 {
            get {
                return ResourceManager.GetString("fr_ProductDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  plus...
        ///
        /// ähnelt.
        /// </summary>
        internal static string fr_ProductDelete3 {
            get {
                return ResourceManager.GetString("fr_ProductDelete3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Êtes-vous sûr de vouloir continuer ? ähnelt.
        /// </summary>
        internal static string fr_ProductDelete4 {
            get {
                return ResourceManager.GetString("fr_ProductDelete4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Un nouveau fichier TraderPlusPriceConfig.json sera créé dans le dossier d&apos;exportation. 
        ///
        ///Etes-vous sûr de vouloir continuer ? ähnelt.
        /// </summary>
        internal static string fr_SaveConfirm {
            get {
                return ResourceManager.GetString("fr_SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tous les produits de la catégorie marquée obtiendront cette valeur ! 
        ///
        ///Etes-vous sûr de vouloir continuer ? ähnelt.
        /// </summary>
        internal static string fr_SetAllWarning {
            get {
                return ResourceManager.GetString("fr_SetAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur ! ähnelt.
        /// </summary>
        internal static string fr_TitleError {
            get {
                return ResourceManager.GetString("fr_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string fr_TitleInfo {
            get {
                return ResourceManager.GetString("fr_TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string fr_TitleQuestion {
            get {
                return ResourceManager.GetString("fr_TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention ! ähnelt.
        /// </summary>
        internal static string fr_TitleWarning {
            get {
                return ResourceManager.GetString("fr_TitleWarning", resourceCulture);
            }
        }
    }
}
