//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Kategorie existiert bereits. ähnelt.
        /// </summary>
        internal static string de_CategoryExists {
            get {
                return ResourceManager.GetString("de_CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen gültigen Kategorienamen ein. ähnelt.
        /// </summary>
        internal static string de_CategoryInvalidName {
            get {
                return ResourceManager.GetString("de_CategoryInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Produkte gefunden in Kategorie &apos; ähnelt.
        /// </summary>
        internal static string de_CategoryNoProduct {
            get {
                return ResourceManager.GetString("de_CategoryNoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei war fehlerhaft und wurde nicht importiert! ähnelt.
        /// </summary>
        internal static string de_ImportFail {
            get {
                return ResourceManager.GetString("de_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; wurde erfolgreich importiert! ähnelt.
        /// </summary>
        internal static string de_ImportSuccess {
            get {
                return ResourceManager.GetString("de_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige(s) Zeichen &apos; ähnelt.
        /// </summary>
        internal static string de_InvalidCharacters {
            get {
                return ResourceManager.GetString("de_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; wurde gelöscht! ähnelt.
        /// </summary>
        internal static string de_InvalidCharacters2 {
            get {
                return ResourceManager.GetString("de_InvalidCharacters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leerer Wert erkannt! Kein Export möglich, wenn der Wert nicht korrekt ist! ähnelt.
        /// </summary>
        internal static string de_InvalidEmptyValue {
            get {
                return ResourceManager.GetString("de_InvalidEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Zahlenformat! Kein Export möglich, wenn der Wert nicht korrekt ist! ähnelt.
        /// </summary>
        internal static string de_InvalidNumberFormat {
            get {
                return ResourceManager.GetString("de_InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner existiert nicht! ähnelt.
        /// </summary>
        internal static string de_NoExistingFolder {
            get {
                return ResourceManager.GetString("de_NoExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Markierte Produkte wurden gelöscht! ähnelt.
        /// </summary>
        internal static string de_ProductDeleteSuccess {
            get {
                return ResourceManager.GetString("de_ProductDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; existiert bereits in Kategorie &apos; ähnelt.
        /// </summary>
        internal static string de_ProductExists {
            get {
                return ResourceManager.GetString("de_ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte fülle alle benötigten Textboxen! ähnelt.
        /// </summary>
        internal static string de_ProductMissingTextBoxes {
            get {
                return ResourceManager.GetString("de_ProductMissingTextBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle zuerst eine Kategorie. ähnelt.
        /// </summary>
        internal static string de_ProductNoSelectedCategory {
            get {
                return ResourceManager.GetString("de_ProductNoSelectedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Änderungen festgestellt! Es muss keine neue Datei erstellt werden! ähnelt.
        /// </summary>
        internal static string de_SaveFailed {
            get {
                return ResourceManager.GetString("de_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei erfolgreich gespeichert! ähnelt.
        /// </summary>
        internal static string de_SaveSuccess {
            get {
                return ResourceManager.GetString("de_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Produkt enthält &apos; ähnelt.
        /// </summary>
        internal static string de_SearchNoResult {
            get {
                return ResourceManager.GetString("de_SearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gib einen Suchbegriff ein. ähnelt.
        /// </summary>
        internal static string de_SearchNoTerm {
            get {
                return ResourceManager.GetString("de_SearchNoTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich gespeichert! ähnelt.
        /// </summary>
        internal static string de_SettingsSaved {
            get {
                return ResourceManager.GetString("de_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xscr33mLabs wurde erfolgreich gestartet! ähnelt.
        /// </summary>
        internal static string de_Startup {
            get {
                return ResourceManager.GetString("de_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The category already exists. ähnelt.
        /// </summary>
        internal static string en_CategoryExists {
            get {
                return ResourceManager.GetString("en_CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid category name. ähnelt.
        /// </summary>
        internal static string en_CategoryInvalidName {
            get {
                return ResourceManager.GetString("en_CategoryInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No products found in category &apos; ähnelt.
        /// </summary>
        internal static string en_CategoryNoProduct {
            get {
                return ResourceManager.GetString("en_CategoryNoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file was faulty and was not imported! ähnelt.
        /// </summary>
        internal static string en_ImportFail {
            get {
                return ResourceManager.GetString("en_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; successfully imported! ähnelt.
        /// </summary>
        internal static string en_ImportSuccess {
            get {
                return ResourceManager.GetString("en_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid character(s) &apos; ähnelt.
        /// </summary>
        internal static string en_InvalidCharacters {
            get {
                return ResourceManager.GetString("en_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; has been deleted! ähnelt.
        /// </summary>
        internal static string en_InvalidCharacters2 {
            get {
                return ResourceManager.GetString("en_InvalidCharacters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty value detected! No export possible if the value is not correct! ähnelt.
        /// </summary>
        internal static string en_InvalidEmptyValue {
            get {
                return ResourceManager.GetString("en_InvalidEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid number format! No export possible if the value is not correct! ähnelt.
        /// </summary>
        internal static string en_InvalidNumberFormat {
            get {
                return ResourceManager.GetString("en_InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder does not exist! ähnelt.
        /// </summary>
        internal static string en_NoExistingFolder {
            get {
                return ResourceManager.GetString("en_NoExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marked Products have been deleted! ähnelt.
        /// </summary>
        internal static string en_ProductDeleteSuccess {
            get {
                return ResourceManager.GetString("en_ProductDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; already exists in the category &apos; ähnelt.
        /// </summary>
        internal static string en_ProductExists {
            get {
                return ResourceManager.GetString("en_ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please fill all required textboxes! ähnelt.
        /// </summary>
        internal static string en_ProductMissingTextBoxes {
            get {
                return ResourceManager.GetString("en_ProductMissingTextBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a category. ähnelt.
        /// </summary>
        internal static string en_ProductNoSelectedCategory {
            get {
                return ResourceManager.GetString("en_ProductNoSelectedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No changes detected! There is no need to create a new file! ähnelt.
        /// </summary>
        internal static string en_SaveFailed {
            get {
                return ResourceManager.GetString("en_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data successfully saved! ähnelt.
        /// </summary>
        internal static string en_SaveSuccess {
            get {
                return ResourceManager.GetString("en_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No product contains &apos; ähnelt.
        /// </summary>
        internal static string en_SearchNoResult {
            get {
                return ResourceManager.GetString("en_SearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a search term. ähnelt.
        /// </summary>
        internal static string en_SearchNoTerm {
            get {
                return ResourceManager.GetString("en_SearchNoTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings saved successfully! ähnelt.
        /// </summary>
        internal static string en_SettingsSaved {
            get {
                return ResourceManager.GetString("en_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xscr33mLabs successfully started! ähnelt.
        /// </summary>
        internal static string en_Startup {
            get {
                return ResourceManager.GetString("en_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La catégorie existe déjà. ähnelt.
        /// </summary>
        internal static string fr_CategoryExists {
            get {
                return ResourceManager.GetString("fr_CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veuillez saisir un nom de catégorie valide. ähnelt.
        /// </summary>
        internal static string fr_CategoryInvalidName {
            get {
                return ResourceManager.GetString("fr_CategoryInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aucun produit trouvé dans la catégorie &apos; ähnelt.
        /// </summary>
        internal static string fr_CategoryNoProduct {
            get {
                return ResourceManager.GetString("fr_CategoryNoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le fichier était erroné et n&apos;a pas été importé ! ähnelt.
        /// </summary>
        internal static string fr_ImportFail {
            get {
                return ResourceManager.GetString("fr_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; a été importé avec succès! ähnelt.
        /// </summary>
        internal static string fr_ImportSuccess {
            get {
                return ResourceManager.GetString("fr_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caractère(s) non valide(s) &apos; ähnelt.
        /// </summary>
        internal static string fr_InvalidCharacters {
            get {
                return ResourceManager.GetString("fr_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a été supprimée ! ähnelt.
        /// </summary>
        internal static string fr_InvalidCharacters2 {
            get {
                return ResourceManager.GetString("fr_InvalidCharacters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valeur vide détectée ! Aucune exportation possible si la valeur n&apos;est pas correcte ! ähnelt.
        /// </summary>
        internal static string fr_InvalidEmptyValue {
            get {
                return ResourceManager.GetString("fr_InvalidEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format de nombre invalide ! Aucune exportation possible si la valeur n&apos;est pas correcte ! ähnelt.
        /// </summary>
        internal static string fr_InvalidNumberFormat {
            get {
                return ResourceManager.GetString("fr_InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le dossier n&apos;existe pas ! ähnelt.
        /// </summary>
        internal static string fr_NoExistingFolder {
            get {
                return ResourceManager.GetString("fr_NoExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Les produits marqués ont été supprimés ! ähnelt.
        /// </summary>
        internal static string fr_ProductDeleteSuccess {
            get {
                return ResourceManager.GetString("fr_ProductDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; existe déjà dans la catégorie &apos; ähnelt.
        /// </summary>
        internal static string fr_ProductExists {
            get {
                return ResourceManager.GetString("fr_ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veuillez remplir toutes les zones de texte requises ! ähnelt.
        /// </summary>
        internal static string fr_ProductMissingTextBoxes {
            get {
                return ResourceManager.GetString("fr_ProductMissingTextBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veuillez sélectionner une catégorie. ähnelt.
        /// </summary>
        internal static string fr_ProductNoSelectedCategory {
            get {
                return ResourceManager.GetString("fr_ProductNoSelectedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aucun changement n&apos;a été détecté ! Il n&apos;est pas nécessaire de créer un nouveau fichier ! ähnelt.
        /// </summary>
        internal static string fr_SaveFailed {
            get {
                return ResourceManager.GetString("fr_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Données sauvegardées avec succès ! ähnelt.
        /// </summary>
        internal static string fr_SaveSuccess {
            get {
                return ResourceManager.GetString("fr_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aucun produit ne contient de &apos; ähnelt.
        /// </summary>
        internal static string fr_SearchNoResult {
            get {
                return ResourceManager.GetString("fr_SearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veuillez saisir un terme de recherche. ähnelt.
        /// </summary>
        internal static string fr_SearchNoTerm {
            get {
                return ResourceManager.GetString("fr_SearchNoTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paramètres enregistrés avec succès ! ähnelt.
        /// </summary>
        internal static string fr_SettingsSaved {
            get {
                return ResourceManager.GetString("fr_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xscr33mLabs a été lancé avec succès ! ähnelt.
        /// </summary>
        internal static string fr_Startup {
            get {
                return ResourceManager.GetString("fr_Startup", resourceCulture);
            }
        }
    }
}
