//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.SettingsForm", typeof(SettingsForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deaktiviere Vorschau ähnelt.
        /// </summary>
        internal static string de_CheckBoxPreviewDisable {
            get {
                return ResourceManager.GetString("de_CheckBoxPreviewDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviere Vorschau ähnelt.
        /// </summary>
        internal static string de_CheckBoxPreviewEnable {
            get {
                return ResourceManager.GetString("de_CheckBoxPreviewEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verstecke Kategorie ähnelt.
        /// </summary>
        internal static string de_CheckBoxShowCategoriesDisable {
            get {
                return ResourceManager.GetString("de_CheckBoxShowCategoriesDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige Kategorie ähnelt.
        /// </summary>
        internal static string de_CheckBoxShowCategoriesEnable {
            get {
                return ResourceManager.GetString("de_CheckBoxShowCategoriesEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorien ähnelt.
        /// </summary>
        internal static string de_GroupBoxCategories {
            get {
                return ResourceManager.GetString("de_GroupBoxCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfe EULA ähnelt.
        /// </summary>
        internal static string de_GroupBoxEULA {
            get {
                return ResourceManager.GetString("de_GroupBoxEULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string de_GroupBoxLanguage {
            get {
                return ResourceManager.GetString("de_GroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        internal static string de_GroupBoxOptions {
            get {
                return ResourceManager.GetString("de_GroupBoxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string de_SettingsTitle {
            get {
                return ResourceManager.GetString("de_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Preview ähnelt.
        /// </summary>
        internal static string en_CheckBoxPreviewDisable {
            get {
                return ResourceManager.GetString("en_CheckBoxPreviewDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Preview ähnelt.
        /// </summary>
        internal static string en_CheckBoxPreviewEnable {
            get {
                return ResourceManager.GetString("en_CheckBoxPreviewEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Category ähnelt.
        /// </summary>
        internal static string en_CheckBoxShowCategoriesDisable {
            get {
                return ResourceManager.GetString("en_CheckBoxShowCategoriesDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Category ähnelt.
        /// </summary>
        internal static string en_CheckBoxShowCategoriesEnable {
            get {
                return ResourceManager.GetString("en_CheckBoxShowCategoriesEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        internal static string en_GroupBoxCategories {
            get {
                return ResourceManager.GetString("en_GroupBoxCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Review EULA ähnelt.
        /// </summary>
        internal static string en_GroupBoxEULA {
            get {
                return ResourceManager.GetString("en_GroupBoxEULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string en_GroupBoxLanguage {
            get {
                return ResourceManager.GetString("en_GroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string en_GroupBoxOptions {
            get {
                return ResourceManager.GetString("en_GroupBoxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string en_SettingsTitle {
            get {
                return ResourceManager.GetString("en_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Désactiver l&apos;aperçu ähnelt.
        /// </summary>
        internal static string fr_CheckBoxPreviewDisable {
            get {
                return ResourceManager.GetString("fr_CheckBoxPreviewDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activer l&apos;aperçu ähnelt.
        /// </summary>
        internal static string fr_CheckBoxPreviewEnable {
            get {
                return ResourceManager.GetString("fr_CheckBoxPreviewEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catégorie cachée ähnelt.
        /// </summary>
        internal static string fr_CheckBoxShowCategoriesDisable {
            get {
                return ResourceManager.GetString("fr_CheckBoxShowCategoriesDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Afficher la catégories ähnelt.
        /// </summary>
        internal static string fr_CheckBoxShowCategoriesEnable {
            get {
                return ResourceManager.GetString("fr_CheckBoxShowCategoriesEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catégories ähnelt.
        /// </summary>
        internal static string fr_GroupBoxCategories {
            get {
                return ResourceManager.GetString("fr_GroupBoxCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Réviser le CLUF ähnelt.
        /// </summary>
        internal static string fr_GroupBoxEULA {
            get {
                return ResourceManager.GetString("fr_GroupBoxEULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Langue ähnelt.
        /// </summary>
        internal static string fr_GroupBoxLanguage {
            get {
                return ResourceManager.GetString("fr_GroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string fr_GroupBoxOptions {
            get {
                return ResourceManager.GetString("fr_GroupBoxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Préférences ähnelt.
        /// </summary>
        internal static string fr_SettingsTitle {
            get {
                return ResourceManager.GetString("fr_SettingsTitle", resourceCulture);
            }
        }
    }
}
