//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SplashForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SplashForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.SplashForm", typeof(SplashForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf laufende Instanz prüfen... ähnelt.
        /// </summary>
        internal static string de_CheckInstance {
            get {
                return ResourceManager.GetString("de_CheckInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach Updates suchen... ähnelt.
        /// </summary>
        internal static string de_CheckUpdate {
            get {
                return ResourceManager.GetString("de_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte TraderPlusEditor.... ähnelt.
        /// </summary>
        internal static string de_Finishing {
            get {
                return ResourceManager.GetString("de_Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf Pfade prüfen... ähnelt.
        /// </summary>
        internal static string de_GeneratePath {
            get {
                return ResourceManager.GetString("de_GeneratePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialisiere... ähnelt.
        /// </summary>
        internal static string de_Initializing {
            get {
                return ResourceManager.GetString("de_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte EULA akzeptieren... ähnelt.
        /// </summary>
        internal static string de_WaitForEula {
            get {
                return ResourceManager.GetString("de_WaitForEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for running instance... ähnelt.
        /// </summary>
        internal static string en_CheckInstance {
            get {
                return ResourceManager.GetString("en_CheckInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for updates... ähnelt.
        /// </summary>
        internal static string en_CheckUpdate {
            get {
                return ResourceManager.GetString("en_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launching TraderPlusEditor.... ähnelt.
        /// </summary>
        internal static string en_Finishing {
            get {
                return ResourceManager.GetString("en_Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for Paths... ähnelt.
        /// </summary>
        internal static string en_GeneratePath {
            get {
                return ResourceManager.GetString("en_GeneratePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing... ähnelt.
        /// </summary>
        internal static string en_Initializing {
            get {
                return ResourceManager.GetString("en_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please accept the eula... ähnelt.
        /// </summary>
        internal static string en_WaitForEula {
            get {
                return ResourceManager.GetString("en_WaitForEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vérification de l&apos;instance en cours... ähnelt.
        /// </summary>
        internal static string fr_CheckInstance {
            get {
                return ResourceManager.GetString("fr_CheckInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vérifier les mises à jour... ähnelt.
        /// </summary>
        internal static string fr_CheckUpdate {
            get {
                return ResourceManager.GetString("fr_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lancer TraderPlusEditor... ähnelt.
        /// </summary>
        internal static string fr_Finishing {
            get {
                return ResourceManager.GetString("fr_Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vérifier les chemins... ähnelt.
        /// </summary>
        internal static string fr_GeneratePath {
            get {
                return ResourceManager.GetString("fr_GeneratePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialiser... ähnelt.
        /// </summary>
        internal static string fr_Initializing {
            get {
                return ResourceManager.GetString("fr_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veuillez accepter l&apos;eula... ähnelt.
        /// </summary>
        internal static string fr_WaitForEula {
            get {
                return ResourceManager.GetString("fr_WaitForEula", resourceCulture);
            }
        }
    }
}
