//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TPVerifRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TPVerifRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.TPVerifRes", typeof(TPVerifRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Schlüssel &quot;CategoryName&quot; konnte in der folgenden Kategorie nicht gefunden werden:  ähnelt.
        /// </summary>
        internal static string de_categoryMessage {
            get {
                return ResourceManager.GetString("de_categoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Schlüssel &quot;Products&quot; konnte in der folgenden Kategorie nicht gefunden werden:  ähnelt.
        /// </summary>
        internal static string de_categoryMessage1 {
            get {
                return ResourceManager.GetString("de_categoryMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das folgende Produkt ist fehlerhaft:  ähnelt.
        /// </summary>
        internal static string de_ProductMessage {
            get {
                return ResourceManager.GetString("de_ProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorie des Produkts:  ähnelt.
        /// </summary>
        internal static string de_ProductMessage1 {
            get {
                return ResourceManager.GetString("de_ProductMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte stelle sicher, dass mindestens fünf Werte für das Produkt vorhanden sind!
        ///Beispiel: &quot;CLASSNAME,1,-1,1,5000,500&quot; ähnelt.
        /// </summary>
        internal static string de_ProductMessage2 {
            get {
                return ResourceManager.GetString("de_ProductMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der folgende Schlüssel wurde nicht gefunden:  ähnelt.
        /// </summary>
        internal static string de_requiredKeysMessage {
            get {
                return ResourceManager.GetString("de_requiredKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///Möglicher Schreibfehler bei dem folgenden Schlüssel:  ähnelt.
        /// </summary>
        internal static string de_requiredKeysMessage1 {
            get {
                return ResourceManager.GetString("de_requiredKeysMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möglicher Schreibfehler bei dem folgenden Schlüssel:  ähnelt.
        /// </summary>
        internal static string de_requiredKeysMessageLog {
            get {
                return ResourceManager.GetString("de_requiredKeysMessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Validieren der TraderPlusPriceConfig.json:  ähnelt.
        /// </summary>
        internal static string de_TPVerifExept {
            get {
                return ResourceManager.GetString("de_TPVerifExept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The key &quot;CategoryName&quot; could not be found in the following category:  ähnelt.
        /// </summary>
        internal static string en_categoryMessage {
            get {
                return ResourceManager.GetString("en_categoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The key &quot;Products&quot; could not be found in the following category:  ähnelt.
        /// </summary>
        internal static string en_categoryMessage1 {
            get {
                return ResourceManager.GetString("en_categoryMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following product is incorrect:  ähnelt.
        /// </summary>
        internal static string en_ProductMessage {
            get {
                return ResourceManager.GetString("en_ProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product category:  ähnelt.
        /// </summary>
        internal static string en_ProductMessage1 {
            get {
                return ResourceManager.GetString("en_ProductMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please make sure that there are at least five values for the product!
        ///Example: &quot;CLASSNAME,1,-1,1,5000,500&quot; ähnelt.
        /// </summary>
        internal static string en_ProductMessage2 {
            get {
                return ResourceManager.GetString("en_ProductMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following key was not found:  ähnelt.
        /// </summary>
        internal static string en_requiredKeysMessage {
            get {
                return ResourceManager.GetString("en_requiredKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///Possible typing error in the following key:  ähnelt.
        /// </summary>
        internal static string en_requiredKeysMessage1 {
            get {
                return ResourceManager.GetString("en_requiredKeysMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Possible typing error in the following key:  ähnelt.
        /// </summary>
        internal static string en_requiredKeysMessageLog {
            get {
                return ResourceManager.GetString("en_requiredKeysMessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error validating the TraderPlusPriceConfig.json:  ähnelt.
        /// </summary>
        internal static string en_TPVerifExept {
            get {
                return ResourceManager.GetString("en_TPVerifExept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La clé &quot;NomCatégorie&quot; n&apos;a pas pu être trouvée dans la catégorie suivante :  ähnelt.
        /// </summary>
        internal static string fr_categoryMessage {
            get {
                return ResourceManager.GetString("fr_categoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La clé &quot;Produits&quot; n&apos;a pas pu être trouvée dans la catégorie suivante :  ähnelt.
        /// </summary>
        internal static string fr_categoryMessage1 {
            get {
                return ResourceManager.GetString("fr_categoryMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le produit suivant est incorrect :  ähnelt.
        /// </summary>
        internal static string fr_ProductMessage {
            get {
                return ResourceManager.GetString("fr_ProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catégorie de produit :  ähnelt.
        /// </summary>
        internal static string fr_ProductMessage1 {
            get {
                return ResourceManager.GetString("fr_ProductMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veillez à ce qu&apos;il y ait au moins cinq valeurs pour le produit !
        ///Exemple : &quot;CLASSNAME,1,-1,1,5000,500&quot; ähnelt.
        /// </summary>
        internal static string fr_ProductMessage2 {
            get {
                return ResourceManager.GetString("fr_ProductMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La clé suivante n&apos;a pas été trouvée :  ähnelt.
        /// </summary>
        internal static string fr_requiredKeysMessage {
            get {
                return ResourceManager.GetString("fr_requiredKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///Erreur de frappe possible dans la clé suivante :  ähnelt.
        /// </summary>
        internal static string fr_requiredKeysMessage1 {
            get {
                return ResourceManager.GetString("fr_requiredKeysMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur de frappe possible dans la clé suivante :  ähnelt.
        /// </summary>
        internal static string fr_requiredKeysMessageLog {
            get {
                return ResourceManager.GetString("fr_requiredKeysMessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur de validation du fichier TraderPlusPriceConfig.json :  ähnelt.
        /// </summary>
        internal static string fr_TPVerifExept {
            get {
                return ResourceManager.GetString("fr_TPVerifExept", resourceCulture);
            }
        }
    }
}
