//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderPlusEditor._Core._Language._Stringtables {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateCheckRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateCheckRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderPlusEditor._Core._Language._Stringtables.UpdateCheckRes", typeof(UpdateCheckRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Browser konnte nicht gestartet werden. ähnelt.
        /// </summary>
        internal static string de_BrowserError {
            get {
                return ResourceManager.GetString("de_BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine neuere Version ist verfügbar!
        ///
        ///Möchten Sie sie jetzt herunterladen? ähnelt.
        /// </summary>
        internal static string de_NewVersion {
            get {
                return ResourceManager.GetString("de_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein neues Update gefunden! ähnelt.
        /// </summary>
        internal static string de_NoUpdate {
            get {
                return ResourceManager.GetString("de_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Suche nach Updates:  ähnelt.
        /// </summary>
        internal static string de_UpdateError {
            get {
                return ResourceManager.GetString("de_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update verfügbar! ähnelt.
        /// </summary>
        internal static string de_UpdateTitle {
            get {
                return ResourceManager.GetString("de_UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browser could not be started. ähnelt.
        /// </summary>
        internal static string en_BrowserError {
            get {
                return ResourceManager.GetString("en_BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A newer version is available!
        ///
        ///Do you want to download it now? ähnelt.
        /// </summary>
        internal static string en_NewVersion {
            get {
                return ResourceManager.GetString("en_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No new update found! ähnelt.
        /// </summary>
        internal static string en_NoUpdate {
            get {
                return ResourceManager.GetString("en_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while checking for updates:  ähnelt.
        /// </summary>
        internal static string en_UpdateError {
            get {
                return ResourceManager.GetString("en_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update available! ähnelt.
        /// </summary>
        internal static string en_UpdateTitle {
            get {
                return ResourceManager.GetString("en_UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Le navigateur n&apos;a pas pu être démarré. ähnelt.
        /// </summary>
        internal static string fr_BrowserError {
            get {
                return ResourceManager.GetString("fr_BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Une nouvelle version est disponible !
        ///
        ///Voulez-vous la télécharger maintenant ? ähnelt.
        /// </summary>
        internal static string fr_NewVersion {
            get {
                return ResourceManager.GetString("fr_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aucune nouvelle mise à jour n&apos;a été trouvée ! ähnelt.
        /// </summary>
        internal static string fr_NoUpdate {
            get {
                return ResourceManager.GetString("fr_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreur lors de la vérification des mises à jour :  ähnelt.
        /// </summary>
        internal static string fr_UpdateError {
            get {
                return ResourceManager.GetString("fr_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mise à jour disponible ! ähnelt.
        /// </summary>
        internal static string fr_UpdateTitle {
            get {
                return ResourceManager.GetString("fr_UpdateTitle", resourceCulture);
            }
        }
    }
}
